[tools]
# YAML
uv = "latest"       # for install yamllint
yamllint = "latest"

# Markdown
"npm:markdownlint-cli" = "latest"

# JSON
biome = "latest"

# GitHub Actions
actionlint = "latest"
shellcheck = "latest"

# Go
go = "1.24"
golangci-lint = "2"

# Other tools
lefthook = "latest"
